// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: photos.sql

package sqlite

import (
	"context"
	"database/sql"
	"time"
)

const createPhoto = `-- name: CreatePhoto :one
INSERT INTO photos (
    file_path, file_name, file_size, file_mtime, format,
    width, height, captured_at, camera_make, camera_model, lens_model,
    focal_length, aperture, shutter_speed, iso, orientation,
    gps_latitude, gps_longitude, fingerprint, cache_status
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, file_path, file_name, file_size, file_mtime, format,
    width, height, captured_at, camera_make, camera_model, lens_model,
    focal_length, aperture, shutter_speed, iso, orientation,
    gps_latitude, gps_longitude, fingerprint, scanned_at, cache_status
`

type CreatePhotoParams struct {
	FilePath     string          `json:"file_path"`
	FileName     string          `json:"file_name"`
	FileSize     int64           `json:"file_size"`
	FileMtime    time.Time       `json:"file_mtime"`
	Format       string          `json:"format"`
	Width        sql.NullInt64   `json:"width"`
	Height       sql.NullInt64   `json:"height"`
	CapturedAt   sql.NullTime    `json:"captured_at"`
	CameraMake   sql.NullString  `json:"camera_make"`
	CameraModel  sql.NullString  `json:"camera_model"`
	LensModel    sql.NullString  `json:"lens_model"`
	FocalLength  sql.NullFloat64 `json:"focal_length"`
	Aperture     sql.NullFloat64 `json:"aperture"`
	ShutterSpeed sql.NullString  `json:"shutter_speed"`
	Iso          sql.NullInt64   `json:"iso"`
	Orientation  sql.NullInt64   `json:"orientation"`
	GpsLatitude  sql.NullFloat64 `json:"gps_latitude"`
	GpsLongitude sql.NullFloat64 `json:"gps_longitude"`
	Fingerprint  string          `json:"fingerprint"`
	CacheStatus  string          `json:"cache_status"`
}

func (q *Queries) CreatePhoto(ctx context.Context, arg CreatePhotoParams) (Photo, error) {
	row := q.db.QueryRowContext(ctx, createPhoto,
		arg.FilePath,
		arg.FileName,
		arg.FileSize,
		arg.FileMtime,
		arg.Format,
		arg.Width,
		arg.Height,
		arg.CapturedAt,
		arg.CameraMake,
		arg.CameraModel,
		arg.LensModel,
		arg.FocalLength,
		arg.Aperture,
		arg.ShutterSpeed,
		arg.Iso,
		arg.Orientation,
		arg.GpsLatitude,
		arg.GpsLongitude,
		arg.Fingerprint,
		arg.CacheStatus,
	)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.FilePath,
		&i.FileName,
		&i.FileSize,
		&i.FileMtime,
		&i.Format,
		&i.Width,
		&i.Height,
		&i.CapturedAt,
		&i.CameraMake,
		&i.CameraModel,
		&i.LensModel,
		&i.FocalLength,
		&i.Aperture,
		&i.ShutterSpeed,
		&i.Iso,
		&i.Orientation,
		&i.GpsLatitude,
		&i.GpsLongitude,
		&i.Fingerprint,
		&i.ScannedAt,
		&i.CacheStatus,
	)
	return i, err
}

const getPhotoByFilePath = `-- name: GetPhotoByFilePath :one
SELECT id, file_path, file_name, file_size, file_mtime, format,
    width, height, captured_at, camera_make, camera_model, lens_model,
    focal_length, aperture, shutter_speed, iso, orientation,
    gps_latitude, gps_longitude, fingerprint, scanned_at, cache_status
FROM photos WHERE file_path = ?
`

func (q *Queries) GetPhotoByFilePath(ctx context.Context, filePath string) (Photo, error) {
	row := q.db.QueryRowContext(ctx, getPhotoByFilePath, filePath)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.FilePath,
		&i.FileName,
		&i.FileSize,
		&i.FileMtime,
		&i.Format,
		&i.Width,
		&i.Height,
		&i.CapturedAt,
		&i.CameraMake,
		&i.CameraModel,
		&i.LensModel,
		&i.FocalLength,
		&i.Aperture,
		&i.ShutterSpeed,
		&i.Iso,
		&i.Orientation,
		&i.GpsLatitude,
		&i.GpsLongitude,
		&i.Fingerprint,
		&i.ScannedAt,
		&i.CacheStatus,
	)
	return i, err
}

const getPhotoByID = `-- name: GetPhotoByID :one
SELECT id, file_path, file_name, file_size, file_mtime, format,
    width, height, captured_at, camera_make, camera_model, lens_model,
    focal_length, aperture, shutter_speed, iso, orientation,
    gps_latitude, gps_longitude, fingerprint, scanned_at, cache_status
FROM photos WHERE id = ?
`

func (q *Queries) GetPhotoByID(ctx context.Context, id int64) (Photo, error) {
	row := q.db.QueryRowContext(ctx, getPhotoByID, id)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.FilePath,
		&i.FileName,
		&i.FileSize,
		&i.FileMtime,
		&i.Format,
		&i.Width,
		&i.Height,
		&i.CapturedAt,
		&i.CameraMake,
		&i.CameraModel,
		&i.LensModel,
		&i.FocalLength,
		&i.Aperture,
		&i.ShutterSpeed,
		&i.Iso,
		&i.Orientation,
		&i.GpsLatitude,
		&i.GpsLongitude,
		&i.Fingerprint,
		&i.ScannedAt,
		&i.CacheStatus,
	)
	return i, err
}

const listAllFingerprints = `-- name: ListAllFingerprints :many
SELECT file_path, fingerprint FROM photos
`

type ListAllFingerprintsRow struct {
	FilePath    string `json:"file_path"`
	Fingerprint string `json:"fingerprint"`
}

func (q *Queries) ListAllFingerprints(ctx context.Context) ([]ListAllFingerprintsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllFingerprints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllFingerprintsRow
	for rows.Next() {
		var i ListAllFingerprintsRow
		if err := rows.Scan(&i.FilePath, &i.Fingerprint); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingPhotos = `-- name: ListPendingPhotos :many
SELECT id, file_path, file_name, file_size, file_mtime, format,
    width, height, captured_at, camera_make, camera_model, lens_model,
    focal_length, aperture, shutter_speed, iso, orientation,
    gps_latitude, gps_longitude, fingerprint, scanned_at, cache_status
FROM photos
WHERE cache_status = 'pending'
ORDER BY captured_at DESC
LIMIT ?
`

func (q *Queries) ListPendingPhotos(ctx context.Context, limit int64) ([]Photo, error) {
	rows, err := q.db.QueryContext(ctx, listPendingPhotos, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Photo
	for rows.Next() {
		var i Photo
		if err := rows.Scan(
			&i.ID,
			&i.FilePath,
			&i.FileName,
			&i.FileSize,
			&i.FileMtime,
			&i.Format,
			&i.Width,
			&i.Height,
			&i.CapturedAt,
			&i.CameraMake,
			&i.CameraModel,
			&i.LensModel,
			&i.FocalLength,
			&i.Aperture,
			&i.ShutterSpeed,
			&i.Iso,
			&i.Orientation,
			&i.GpsLatitude,
			&i.GpsLongitude,
			&i.Fingerprint,
			&i.ScannedAt,
			&i.CacheStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePhoto = `-- name: UpdatePhoto :exec
UPDATE photos SET
    file_size = ?, file_mtime = ?, format = ?,
    width = ?, height = ?, captured_at = ?,
    camera_make = ?, camera_model = ?, lens_model = ?,
    focal_length = ?, aperture = ?, shutter_speed = ?,
    iso = ?, orientation = ?,
    gps_latitude = ?, gps_longitude = ?,
    fingerprint = ?, scanned_at = CURRENT_TIMESTAMP,
    cache_status = ?
WHERE id = ?
`

type UpdatePhotoParams struct {
	FileSize     int64           `json:"file_size"`
	FileMtime    time.Time       `json:"file_mtime"`
	Format       string          `json:"format"`
	Width        sql.NullInt64   `json:"width"`
	Height       sql.NullInt64   `json:"height"`
	CapturedAt   sql.NullTime    `json:"captured_at"`
	CameraMake   sql.NullString  `json:"camera_make"`
	CameraModel  sql.NullString  `json:"camera_model"`
	LensModel    sql.NullString  `json:"lens_model"`
	FocalLength  sql.NullFloat64 `json:"focal_length"`
	Aperture     sql.NullFloat64 `json:"aperture"`
	ShutterSpeed sql.NullString  `json:"shutter_speed"`
	Iso          sql.NullInt64   `json:"iso"`
	Orientation  sql.NullInt64   `json:"orientation"`
	GpsLatitude  sql.NullFloat64 `json:"gps_latitude"`
	GpsLongitude sql.NullFloat64 `json:"gps_longitude"`
	Fingerprint  string          `json:"fingerprint"`
	CacheStatus  string          `json:"cache_status"`
	ID           int64           `json:"id"`
}

func (q *Queries) UpdatePhoto(ctx context.Context, arg UpdatePhotoParams) error {
	_, err := q.db.ExecContext(ctx, updatePhoto,
		arg.FileSize,
		arg.FileMtime,
		arg.Format,
		arg.Width,
		arg.Height,
		arg.CapturedAt,
		arg.CameraMake,
		arg.CameraModel,
		arg.LensModel,
		arg.FocalLength,
		arg.Aperture,
		arg.ShutterSpeed,
		arg.Iso,
		arg.Orientation,
		arg.GpsLatitude,
		arg.GpsLongitude,
		arg.Fingerprint,
		arg.CacheStatus,
		arg.ID,
	)
	return err
}

const updatePhotoCacheStatus = `-- name: UpdatePhotoCacheStatus :exec
UPDATE photos SET cache_status = ? WHERE id = ?
`

type UpdatePhotoCacheStatusParams struct {
	CacheStatus string `json:"cache_status"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdatePhotoCacheStatus(ctx context.Context, arg UpdatePhotoCacheStatusParams) error {
	_, err := q.db.ExecContext(ctx, updatePhotoCacheStatus, arg.CacheStatus, arg.ID)
	return err
}
