// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlite

import (
	"context"
)

type Querier interface {
	CountUsers(ctx context.Context) (int64, error)
	CreatePhoto(ctx context.Context, arg CreatePhotoParams) (Photo, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetPhotoByFilePath(ctx context.Context, filePath string) (Photo, error)
	GetPhotoByID(ctx context.Context, id int64) (Photo, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListAllFingerprints(ctx context.Context) ([]ListAllFingerprintsRow, error)
	ListPendingPhotos(ctx context.Context, limit int64) ([]Photo, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	Ping(ctx context.Context) error
	UpdateLastLogin(ctx context.Context, id int64) error
	UpdatePhoto(ctx context.Context, arg UpdatePhotoParams) error
	UpdatePhotoCacheStatus(ctx context.Context, arg UpdatePhotoCacheStatusParams) error
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error
}

var _ Querier = (*Queries)(nil)
