// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package sqlite

import (
	"context"
	"database/sql"
	"time"
)

const addPhotoTag = `-- name: AddPhotoTag :exec
INSERT OR IGNORE INTO photo_tags (photo_id, tag_id, created_by)
VALUES (?, ?, ?)
`

type AddPhotoTagParams struct {
	PhotoID   int64 `json:"photo_id"`
	TagID     int64 `json:"tag_id"`
	CreatedBy int64 `json:"created_by"`
}

func (q *Queries) AddPhotoTag(ctx context.Context, arg AddPhotoTagParams) error {
	_, err := q.db.ExecContext(ctx, addPhotoTag, arg.PhotoID, arg.TagID, arg.CreatedBy)
	return err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (name, color, group_id, created_by)
VALUES (?, ?, ?, ?)
RETURNING id, name, color, group_id, created_by, created_at
`

type CreateTagParams struct {
	Name      string         `json:"name"`
	Color     sql.NullString `json:"color"`
	GroupID   sql.NullInt64  `json:"group_id"`
	CreatedBy int64          `json:"created_by"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag,
		arg.Name,
		arg.Color,
		arg.GroupID,
		arg.CreatedBy,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.GroupID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createTagGroup = `-- name: CreateTagGroup :one
INSERT INTO tag_groups (name, sort_order)
VALUES (?, ?)
RETURNING id, name, sort_order, created_at
`

type CreateTagGroupParams struct {
	Name      string `json:"name"`
	SortOrder int64  `json:"sort_order"`
}

func (q *Queries) CreateTagGroup(ctx context.Context, arg CreateTagGroupParams) (TagGroup, error) {
	row := q.db.QueryRowContext(ctx, createTagGroup, arg.Name, arg.SortOrder)
	var i TagGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id = ?
`

func (q *Queries) DeleteTag(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTag, id)
	return err
}

const deleteTagGroup = `-- name: DeleteTagGroup :exec
DELETE FROM tag_groups WHERE id = ?
`

func (q *Queries) DeleteTagGroup(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTagGroup, id)
	return err
}

const getTagByID = `-- name: GetTagByID :one
SELECT t.id, t.name, t.color, t.group_id, t.created_by, t.created_at,
       tg.name AS group_name
FROM tags t
LEFT JOIN tag_groups tg ON tg.id = t.group_id
WHERE t.id = ?
`

type GetTagByIDRow struct {
	ID        int64          `json:"id"`
	Name      string         `json:"name"`
	Color     sql.NullString `json:"color"`
	GroupID   sql.NullInt64  `json:"group_id"`
	CreatedBy int64          `json:"created_by"`
	CreatedAt time.Time      `json:"created_at"`
	GroupName sql.NullString `json:"group_name"`
}

func (q *Queries) GetTagByID(ctx context.Context, id int64) (GetTagByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getTagByID, id)
	var i GetTagByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.GroupID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.GroupName,
	)
	return i, err
}

const getTagGroupByID = `-- name: GetTagGroupByID :one
SELECT id, name, sort_order, created_at
FROM tag_groups WHERE id = ?
`

func (q *Queries) GetTagGroupByID(ctx context.Context, id int64) (TagGroup, error) {
	row := q.db.QueryRowContext(ctx, getTagGroupByID, id)
	var i TagGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const listTagGroups = `-- name: ListTagGroups :many
SELECT id, name, sort_order, created_at
FROM tag_groups ORDER BY sort_order, name
`

func (q *Queries) ListTagGroups(ctx context.Context) ([]TagGroup, error) {
	rows, err := q.db.QueryContext(ctx, listTagGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TagGroup
	for rows.Next() {
		var i TagGroup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT t.id, t.name, t.color, t.group_id, t.created_by, t.created_at,
       tg.name AS group_name
FROM tags t
LEFT JOIN tag_groups tg ON tg.id = t.group_id
ORDER BY COALESCE(tg.sort_order, 999999), t.name
`

type ListTagsRow struct {
	ID        int64          `json:"id"`
	Name      string         `json:"name"`
	Color     sql.NullString `json:"color"`
	GroupID   sql.NullInt64  `json:"group_id"`
	CreatedBy int64          `json:"created_by"`
	CreatedAt time.Time      `json:"created_at"`
	GroupName sql.NullString `json:"group_name"`
}

func (q *Queries) ListTags(ctx context.Context) ([]ListTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagsRow
	for rows.Next() {
		var i ListTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.GroupID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForPhoto = `-- name: ListTagsForPhoto :many
SELECT t.id, t.name, t.color, t.group_id, t.created_by, t.created_at,
       tg.name AS group_name
FROM photo_tags pt
JOIN tags t ON t.id = pt.tag_id
LEFT JOIN tag_groups tg ON tg.id = t.group_id
WHERE pt.photo_id = ?
ORDER BY t.name
`

type ListTagsForPhotoRow struct {
	ID        int64          `json:"id"`
	Name      string         `json:"name"`
	Color     sql.NullString `json:"color"`
	GroupID   sql.NullInt64  `json:"group_id"`
	CreatedBy int64          `json:"created_by"`
	CreatedAt time.Time      `json:"created_at"`
	GroupName sql.NullString `json:"group_name"`
}

func (q *Queries) ListTagsForPhoto(ctx context.Context, photoID int64) ([]ListTagsForPhotoRow, error) {
	rows, err := q.db.QueryContext(ctx, listTagsForPhoto, photoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagsForPhotoRow
	for rows.Next() {
		var i ListTagsForPhotoRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.GroupID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removePhotoTag = `-- name: RemovePhotoTag :exec
DELETE FROM photo_tags WHERE photo_id = ? AND tag_id = ?
`

type RemovePhotoTagParams struct {
	PhotoID int64 `json:"photo_id"`
	TagID   int64 `json:"tag_id"`
}

func (q *Queries) RemovePhotoTag(ctx context.Context, arg RemovePhotoTagParams) error {
	_, err := q.db.ExecContext(ctx, removePhotoTag, arg.PhotoID, arg.TagID)
	return err
}

const updateTag = `-- name: UpdateTag :exec
UPDATE tags SET name = ?, color = ?, group_id = ? WHERE id = ?
`

type UpdateTagParams struct {
	Name    string         `json:"name"`
	Color   sql.NullString `json:"color"`
	GroupID sql.NullInt64  `json:"group_id"`
	ID      int64          `json:"id"`
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) error {
	_, err := q.db.ExecContext(ctx, updateTag,
		arg.Name,
		arg.Color,
		arg.GroupID,
		arg.ID,
	)
	return err
}

const updateTagGroup = `-- name: UpdateTagGroup :exec
UPDATE tag_groups SET name = ?, sort_order = ? WHERE id = ?
`

type UpdateTagGroupParams struct {
	Name      string `json:"name"`
	SortOrder int64  `json:"sort_order"`
	ID        int64  `json:"id"`
}

func (q *Queries) UpdateTagGroup(ctx context.Context, arg UpdateTagGroupParams) error {
	_, err := q.db.ExecContext(ctx, updateTagGroup, arg.Name, arg.SortOrder, arg.ID)
	return err
}
